### ISSUE TITLE
Update package.json engines for node.js 23.X

### ISSUE THREAD

**Issue by vpmedia** [RobinTail/zod-sockets#326]
Getting the following warning from npm:

```
npm warn EBADENGINE Unsupported engine {
npm warn EBADENGINE   package: 'zod-sockets@2.1.0',
npm warn EBADENGINE   required: { node: '^18.18.0 || ^20.9.0 || ^22.0.0' },
npm warn EBADENGINE   current: { node: 'v23.1.0', npm: '10.9.0' }
npm warn EBADENGINE }
```

**Comment by vpmedia** [comment]
Thanks for the clarification. In production we are using v22.X, but in my local dev env homebrew auto updated to v23.X so I supposed it is the current stable release. Thanks!

**Comment by RobinTail** [comment]
sure, @vpmedia 
consider `nvm`, so that you can switch between versions easily:

https://formulae.brew.sh/formula/nvm
